### ISSUE TITLE
Question / Bugreport / Request: Support for Geolocation and deviceorientation events in controller

### ISSUE THREAD

**Issue by dreamora** [AirConsole/airconsole-unity-plugin#45]
Sorry if I don't follow certain desired structures.

It is possible I am doing something that is currently not meant to be supported but in my mind and based on different experiments, AirConsole has the potential to be a fantastic 'metaverse game platform' so I would at least like to inquire if it is an error on my side.

## Context 
I hoped to explore 'realworld multiplayer games' and potentially create one or more games on top of AirConsole.

For this I rely on two web apis:
- deviceorientation (through window.addeventlistener)
- Geolocation (through navigator.geolocation) to get GPS coordinates I hope to send to the  server to visualize players / teams on a map for various game ideas.
  - This is blocked currently because the iframe embedding in the Simulator seems to miss certain policies (at least in the web version on the simulator)

## Platform
- Unity 2019.4.40 running the simulator
- OSX 13.5
- iPhone 12 Pro, iOS 16.6, Safari

## How to reproduce

Expand the pong controller.html with

```html
if(navigator.geolocation) {
        let upButton = document.getElementById("up_button");
        geolocationWatch = navigator.geolocation.watchPosition(function(position) {
          downButton.innerText = `Latitude: ${position.coords.latitude}; Longitude: ${position.coords.longitude}`;
        }, null, { maximumAge: 5000, timeout: 5000, enableHighAccuracy: true });
      } else {
          console.error("Geolocation is not supported by this browser.");
      }
```

and give the up button id="up_button"

## Issue
When  trying to use a controller with geolocation API I get the following error:

```
feature policy 'Geolocation' check failed for iframe with origin 'http://IP:7842' and allow attribute 'autoplay; microphone; camera'.
```

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/geolocation this would imply that the iframe of the controller gets embedded with insufficient policy rights.
As the controller gets embedded through an iframe, this appears to be an impossible to overcome blockade.

## Question
- Am I doing something wrong?
- Can I somehow impact this to overcome the limitation?
  - if so, what would that be?

**Comment by daniel-n-dream** [comment]
Hi Dreamora,

Thank you for your interest and sorry for the delay in the reply:
- Regarding deviceorientation support, we do support it directly through the AirConsole API (See https://developers.airconsole.com/#!/api, onDeviceMotion())
- For the geolocalization feature, we never had the usecase until now. It is something that we are considering with the car usecase, but as we speak there is no way to get this information.

**Comment by dreamora** [comment]
Hello Daniel

Thank you very much for the reply.

Looking forward to any potential plan that might arise from the car use cases along this line and potentially similar lines that would be fun for metaverse or 'real user meets extended reality' usecases (geolocation and audio in particular - the orientation was meant merely to act as input for audio output and visual hints to guide a user without being glued to the screen while moving through the world)

will close this issue then as there is no action to take.
