### ISSUE TITLE
Websocket Failed.

### ISSUE THREAD

**Issue by AntonLie** [AirConsole/airconsole-unity-plugin#62]
Hello Team,

I tried to connect air console unity.

first time scan with the real phone, and everything going well.

but when I disconnect and try scan new QR code 

I got an error like this:

`WebSocket connection to 'ws://127.0.0.1:7843/api' failed:`

I Already tried to disabled firewall but still not working.

am I missing something to integrate air console?

Thank you Team.

**Comment by marc-n-dream** [comment]
127.0.0.1 is only accessible from the local machine.

The game needs to be reachable from a public url or at least a network IP (normally something like 192.168.XXX.YYY for home networks or 10.0.XXX.YYY for office)
You can find more in the 'how to test' guide at https://developers.airconsole.com/#!/guides/simulator

If you need to test hardware features on the phone like Gyro, your game must be reachable through HTTPS using something like cloudflared or ngrok paid - we have a guide on this at https://developers.airconsole.com/#!/guides/unity-external-access

**Comment by marc-n-dream** [comment]
No

All you need is to find your Network IP (using [ifconfig like this](https://phoenixnap.com/kb/how-to-find-ip-address-linux#:~:text=Using%20ifconfig%20Command,-The%20third%20method&text=The%20system%20displays%20all%20network,may%20notice%20the%20term%20Loopback.) for example and provide the identified IP to the **Local IP Override** in the current version of the AirConsole Unity Plugin -> AirConsole MonoBehaviour in the scene.
